### ISSUE TITLE
Where can we find the PDF for API

### ISSUE THREAD

**Issue by retsyo** [WasatchPhotonics/Python-USB-WP-Raman-Examples#1]
The document says there is http://wasatchdevices.com/wp-content/uploads/2017/02/OEM-WP-Raman-USB-Interface-Spec-Rev1_4.pdf which is missing now

so where can we get the latest doc? Thanks

**Comment by mzieg** [comment]
API link updated in d68d565097a4f70f9af0314917b38a5b06f2445a
